# These are supported funding model platforms

github: ['rosanlent', 'jaabirosman', 'Ribaj', 'FeriEXP']
community_bridge: Rosan-Ribaj
custom: ['https://t.me/osmanibots', 'https://t.me/osmanigroupbot']
